DROP TABLE IF EXISTS DOMICILIOS;
CREATE TABLE DOMICILIOS (
ID INT AUTO_INCREMENT PRIMARY KEY,
CALLE VARCHAR(100) NOT NULL,
NUMERO INT NOT NULL,
LOCALIDAD VARCHAR(100) NOT NULL,
PROVINCIA VARCHAR(100) NOT NULL);

DROP TABLE IF EXISTS PACIENTES;
CREATE TABLE PACIENTES (
ID INT AUTO_INCREMENT PRIMARY KEY,
APELLIDO VARCHAR(100) NOT NULL,
NOMBRE VARCHAR(100) NOT NULL,
EMAIL VARCHAR(100) NOT NULL,
DNI INT NOT NULL,
FECHA DATE NOT NULL,
DOMICILIO_ID INT NOT NULL);

DROP TABLE IF EXISTS ODONTOLOGOS;
CREATE TABLE ODONTOLOGOS (
ID INT AUTO_INCREMENT PRIMARY KEY,
APELLIDO VARCHAR(100) NOT NULL,
NOMBRE VARCHAR(100) NOT NULL,
MATRICULA VARCHAR(50) NOT NULL);

INSERT INTO ODONTOLOGOS (APELLIDO, NOMBRE, MATRICULA)
VALUES ('Muelas','Juan','MP548');
INSERT INTO ODONTOLOGOS (APELLIDO, NOMBRE, MATRICULA)
VALUES ('Diente','Pedro','MP784');

INSERT INTO DOMICILIOS (CALLE,NUMERO,LOCALIDAD,PROVINCIA)
VALUES ('Calle 1',484,'Salta Capital', 'Salta');

INSERT INTO PACIENTES (APELLIDO, NOMBRE, EMAIL, DNI,
FECHA, DOMICILIO_ID) VALUES ('Baspineiro',
'Rodolfo','reb@gmail.com',584,'2022-08-25',1);